//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUFTManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emp_work_time
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> work_shift_id { get; set; }
        public Nullable<System.DateTime> work_date { get; set; }
        public Nullable<bool> is_fix { get; set; }
    }
}
